<?php
/**
 * Contact Page Template Custom Fields
 *
 * @package Ultimate_Restaurant
 * @author  PriceListo
 */

if (function_exists('acf_add_local_field_group')) :

    acf_add_local_field_group(
        array(
            'key'    => 'group_5f18cf277cd34',
            'title'  => 'Home',
            'fields' => array(
                array(
                    'key'               => 'field_home5f1bbca489ad6',
                    'label'             => 'Show/Hide Sections',
                    'name'              => 'home-visible-sections',
                    'type'              => 'checkbox',
                    'instructions'      => 'Uncheck section(s) to be hided from the page!',
                    'required'          => 0,
                    'conditional_logic' => 0,
                    'wrapper'           => array(
                        'width' => '',
                        'class' => '',
                        'id'    => '',
                    ),
                    'choices'           => array(
                        'hero'    => 'Show Hero Section',
                        'about'   => 'Show About Section',
                        'feature' => 'Show Feature Section',
                        'offer'   => 'Show Offer Section',
                    ),
                    'allow_custom'      => 0,
                    'default_value'     => array(
                        0 => 'hero',
                        1 => 'about',
                        2 => 'feature',
                        3 => 'offer',
                    ),
                    'layout'            => 'horizontal',
                    'toggle'            => 0,
                    'return_format'     => 'value',
                    'save_custom'       => 0,
                ),
                array(
                    'key'               => 'field_home5f18d48e35aec',
                    'label'             => 'Hero Section',
                    'name'              => '',
                    'type'              => 'tab',
                    'instructions'      => '',
                    'required'          => 0,
                    'conditional_logic' => array(
                        array(
                            array(
                                'field'    => 'field_home5f1bbca489ad6',
                                'operator' => '==',
                                'value'    => 'hero',
                            ),
                        ),
                    ),
                    'wrapper'           => array(
                        'width' => '',
                        'class' => '',
                        'id'    => '',
                    ),
                    'placement'         => 'top',
                    'endpoint'          => 0,
                ),
                array(
                    'key'               => 'field_home5f18cf8d87b95',
                    'label'             => 'Background',
                    'name'              => 'background-hero',
                    'type'              => 'image',
                    'instructions'      => '',
                    'required'          => 0,
                    'conditional_logic' => 0,
                    'wrapper'           => array(
                        'width' => '',
                        'class' => '',
                        'id'    => '',
                    ),
                    'return_format'     => 'url',
                    'preview_size'      => 'large',
                    'library'           => 'all',
                    'min_width'         => '',
                    'min_height'        => '',
                    'min_size'          => '',
                    'max_width'         => '',
                    'max_height'        => '',
                    'max_size'          => '',
                    'mime_types'        => '',
                    'default_value'     => '',
                ),
                array(
                    'key'               => 'field_home5f18cfeb87b96',
                    'label'             => 'Heading',
                    'name'              => 'heading-hero',
                    'type'              => 'text',
                    'instructions'      => '',
                    'required'          => 0,
                    'conditional_logic' => 0,
                    'wrapper'           => array(
                        'width' => '',
                        'class' => '',
                        'id'    => '',
                    ),
                    'default_value'     => 'We serve quality food',
                    'placeholder'       => '',
                    'prepend'           => '',
                    'append'            => '',
                    'maxlength'         => '',
                ),
                array(
                    'key'               => 'field_home5f18d00b87b97',
                    'label'             => 'Subheading',
                    'name'              => 'subheading-hero',
                    'type'              => 'text',
                    'instructions'      => '',
                    'required'          => 0,
                    'conditional_logic' => 0,
                    'wrapper'           => array(
                        'width' => '',
                        'class' => '',
                        'id'    => '',
                    ),
                    'default_value'     => 'Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry\'s stan',
                    'placeholder'       => '',
                    'prepend'           => '',
                    'append'            => '',
                    'maxlength'         => '',
                ),
                array(
                    'key'               => 'field_home5f18d92035aed',
                    'label'             => 'About Section',
                    'name'              => '',
                    'type'              => 'tab',
                    'instructions'      => '',
                    'required'          => 0,
                    'conditional_logic' => array(
                        array(
                            array(
                                'field'    => 'field_home5f1bbca489ad6',
                                'operator' => '==',
                                'value'    => 'about',
                            ),
                        ),
                    ),
                    'wrapper'           => array(
                        'width' => '',
                        'class' => '',
                        'id'    => '',
                    ),
                    'placement'         => 'top',
                    'endpoint'          => 0,
                ),
                array(
                    'key'               => 'field_home5f18d94435aee',
                    'label'             => 'Image',
                    'name'              => 'about_image',
                    'type'              => 'image',
                    'instructions'      => '',
                    'required'          => 0,
                    'conditional_logic' => 0,
                    'wrapper'           => array(
                        'width' => '',
                        'class' => '',
                        'id'    => '',
                    ),
                    'return_format'     => 'url',
                    'preview_size'      => 'medium',
                    'library'           => 'all',
                    'min_width'         => '',
                    'min_height'        => '',
                    'min_size'          => '',
                    'max_width'         => '',
                    'max_height'        => '',
                    'max_size'          => '',
                    'mime_types'        => '',
                ),
                array(
                    'key'               => 'field_home5f18d9be35aef',
                    'label'             => 'Title',
                    'name'              => 'title-about',
                    'type'              => 'text',
                    'instructions'      => '',
                    'required'          => 0,
                    'conditional_logic' => 0,
                    'wrapper'           => array(
                        'width' => '',
                        'class' => '',
                        'id'    => '',
                    ),
                    'default_value'     => 'Who we are',
                    'placeholder'       => '',
                    'prepend'           => '',
                    'append'            => '',
                    'maxlength'         => '',
                ),
                array(
                    'key' => 'field_home5f4bc27e5f2a4',
                    'label' => 'Subtitle',
                    'name' => 'subtitle-about',
                    'type' => 'text',
                    'instructions' => '',
                    'required' => 0,
                    'conditional_logic' => 0,
                    'wrapper' => array(
                        'width' => '',
                        'class' => '',
                        'id' => '',
                    ),
                    'default_value' => '',
                    'placeholder' => '',
                    'prepend' => '',
                    'append' => '',
                    'maxlength' => '',
                ),
                array(
                    'key'               => 'field_home5f18d9de35af0',
                    'label'             => 'Content',
                    'name'              => 'content-about',
                    'type'              => 'wysiwyg',
                    'instructions'      => '',
                    'required'          => 0,
                    'conditional_logic' => 0,
                    'wrapper'           => array(
                        'width' => '',
                        'class' => '',
                        'id'    => '',
                    ),
                    'default_value'     => 'Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry\'s stan
    
    dard dummy text ever since the 1500s,when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting.dard dummy text ever since the 1500s,when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting.dard dummy text ever since the 1500s,when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting.dard dummy text ever since the 1500s,when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting.dard dummy text ever since the 1500s,ever since the 1500s,when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting.',
                    'tabs'              => 'all',
                    'toolbar'           => 'full',
                    'media_upload'      => 0,
                    'delay'             => 0,
                ),
                array(
                    'key'               => 'field_home5f18da4735af1',
                    'label'             => 'Button Text',
                    'name'              => 'button-text-about',
                    'type'              => 'text',
                    'instructions'      => '',
                    'required'          => 0,
                    'conditional_logic' => 0,
                    'wrapper'           => array(
                        'width' => '',
                        'class' => '',
                        'id'    => '',
                    ),
                    'default_value'     => 'Read More',
                    'placeholder'       => '',
                    'prepend'           => '',
                    'append'            => '',
                    'maxlength'         => '',
                ),
                array(
                    'key'               => 'field_home5f18daa335af2',
                    'label'             => 'Button Link',
                    'name'              => 'button-link-about',
                    'type'              => 'url',
                    'instructions'      => '',
                    'required'          => 0,
                    'conditional_logic' => 0,
                    'wrapper'           => array(
                        'width' => '',
                        'class' => '',
                        'id'    => '',
                    ),
                    'default_value'     => '',
                    'placeholder'       => '',
                ),
                array(
                    'key'               => 'field_home5f18def52b5ad',
                    'label'             => 'Feature Section',
                    'name'              => '',
                    'type'              => 'tab',
                    'instructions'      => '',
                    'required'          => 0,
                    'conditional_logic' => array(
                        array(
                            array(
                                'field'    => 'field_home5f1bbca489ad6',
                                'operator' => '==',
                                'value'    => 'feature',
                            ),
                        ),
                    ),
                    'wrapper'           => array(
                        'width' => '',
                        'class' => '',
                        'id'    => '',
                    ),
                    'placement'         => 'top',
                    'endpoint'          => 0,
                ),
                array(
                    'key'               => 'field_home5f18df062b5ae',
                    'label'             => 'Background',
                    'name'              => 'background-feature',
                    'type'              => 'image',
                    'instructions'      => '',
                    'required'          => 0,
                    'conditional_logic' => 0,
                    'wrapper'           => array(
                        'width' => '',
                        'class' => '',
                        'id'    => '',
                    ),
                    'return_format'     => 'url',
                    'preview_size'      => 'medium',
                    'library'           => 'all',
                    'min_width'         => '',
                    'min_height'        => '',
                    'min_size'          => '',
                    'max_width'         => '',
                    'max_height'        => '',
                    'max_size'          => '',
                    'mime_types'        => '',
                ),
                array(
                    'key'               => 'field_home5f18df472b5af',
                    'label'             => 'Title',
                    'name'              => 'title-feature',
                    'type'              => 'text',
                    'instructions'      => '',
                    'required'          => 0,
                    'conditional_logic' => 0,
                    'wrapper'           => array(
                        'width' => '',
                        'class' => '',
                        'id'    => '',
                    ),
                    'default_value'     => 'Our Food',
                    'placeholder'       => '',
                    'prepend'           => '',
                    'append'            => '',
                    'maxlength'         => '',
                ),
                array(
                    'key'               => 'field_home5f18df622b5b0',
                    'label'             => 'Content',
                    'name'              => 'content-feature',
                    'type'              => 'wysiwyg',
                    'instructions'      => '',
                    'required'          => 0,
                    'conditional_logic' => 0,
                    'wrapper'           => array(
                        'width' => '',
                        'class' => '',
                        'id'    => '',
                    ),
                    'default_value'     => 'dard dummy text ever since the 1500s,when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting.dard dummy text ever since the 1500s,when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, e the 1500s,',
                    'tabs'              => 'all',
                    'toolbar'           => 'full',
                    'media_upload'      => 0,
                    'delay'             => 0,
                ),
                array(
                    'key'               => 'field_home5f18dfc42b5b1',
                    'label'             => 'Button Text',
                    'name'              => 'button-text-feature',
                    'type'              => 'text',
                    'instructions'      => '',
                    'required'          => 0,
                    'conditional_logic' => 0,
                    'wrapper'           => array(
                        'width' => '',
                        'class' => '',
                        'id'    => '',
                    ),
                    'default_value'     => 'See Menu',
                    'placeholder'       => '',
                    'prepend'           => '',
                    'append'            => '',
                    'maxlength'         => '',
                ),
                array(
                    'key'               => 'field_home5f18dfee2b5b2',
                    'label'             => 'Button Link',
                    'name'              => 'button-link-feature',
                    'type'              => 'url',
                    'instructions'      => '',
                    'required'          => 0,
                    'conditional_logic' => 0,
                    'wrapper'           => array(
                        'width' => '',
                        'class' => '',
                        'id'    => '',
                    ),
                    'default_value'     => '',
                    'placeholder'       => '',
                ),
                array(
                    'key'               => 'field_home5f18ea9751fcd',
                    'label'             => 'Offer Section',
                    'name'              => '',
                    'type'              => 'tab',
                    'instructions'      => '',
                    'required'          => 0,
                    'conditional_logic' => array(
                        array(
                            array(
                                'field'    => 'field_home5f1bbca489ad6',
                                'operator' => '==',
                                'value'    => 'offer',
                            ),
                        ),
                    ),
                    'wrapper'           => array(
                        'width' => '',
                        'class' => '',
                        'id'    => '',
                    ),
                    'placement'         => 'top',
                    'endpoint'          => 0,
                ),
                array(
                    'key'               => 'field_home5f18eaa451fce',
                    'label'             => 'Title',
                    'name'              => 'title-offer',
                    'type'              => 'text',
                    'instructions'      => '',
                    'required'          => 0,
                    'conditional_logic' => 0,
                    'wrapper'           => array(
                        'width' => '',
                        'class' => '',
                        'id'    => '',
                    ),
                    'default_value'     => 'What We Offer',
                    'placeholder'       => '',
                    'prepend'           => '',
                    'append'            => '',
                    'maxlength'         => '',
                ),
                array(
                    'key'               => 'field_home5f18eac451fcf',
                    'label'             => 'Content',
                    'name'              => 'content-offer',
                    'type'              => 'wysiwyg',
                    'instructions'      => '',
                    'required'          => 0,
                    'conditional_logic' => 0,
                    'wrapper'           => array(
                        'width' => '',
                        'class' => '',
                        'id'    => '',
                    ),
                    'default_value'     => 'dard dummy text ever since the 1500s,when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting.dard dummy text ever since the 1500s,when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, e the 1500s,',
                    'tabs'              => 'all',
                    'toolbar'           => 'full',
                    'media_upload'      => 0,
                    'delay'             => 0,
                ),
                array(
                    'key'               => 'field_home5f18eaf051fd0',
                    'label'             => 'Food Category',
                    'name'              => 'food-categories',
                    'type'              => 'group',
                    'instructions'      => '',
                    'required'          => 0,
                    'conditional_logic' => 0,
                    'wrapper'           => array(
                        'width' => '',
                        'class' => '',
                        'id'    => '',
                    ),
                    'layout'            => 'block',
                    'sub_fields'        => array(
                        array(
                            'key'               => 'field_home5f18eb2351fd1',
                            'label'             => 'Category 1',
                            'name'              => '',
                            'type'              => 'tab',
                            'instructions'      => '',
                            'required'          => 0,
                            'conditional_logic' => 0,
                            'wrapper'           => array(
                                'width' => '',
                                'class' => '',
                                'id'    => '',
                            ),
                            'placement'         => 'top',
                            'endpoint'          => 0,
                        ),
                        array(
                            'key'               => 'field_home5f18eb8951fd2',
                            'label'             => 'Food Category title',
                            'name'              => 'food-category-title-1',
                            'type'              => 'text',
                            'instructions'      => '',
                            'required'          => 0,
                            'conditional_logic' => 0,
                            'wrapper'           => array(
                                'width' => '',
                                'class' => '',
                                'id'    => '',
                            ),
                            'default_value'     => 'Italian Cousine',
                            'placeholder'       => '',
                            'prepend'           => '',
                            'append'            => '',
                            'maxlength'         => '',
                        ),
                        array(
                            'key'               => 'field_home5f18ebbc51fd3',
                            'label'             => 'Food Category Icon',
                            'name'              => 'food-category-icon-1',
                            'type'              => 'image',
                            'instructions'      => '',
                            'required'          => 0,
                            'conditional_logic' => 0,
                            'wrapper'           => array(
                                'width' => '',
                                'class' => '',
                                'id'    => '',
                            ),
                            'return_format'     => 'array',
                            'preview_size'      => 'thumbnail',
                            'library'           => 'all',
                            'min_width'         => '',
                            'min_height'        => '',
                            'min_size'          => '',
                            'max_width'         => '',
                            'max_height'        => '',
                            'max_size'          => '',
                            'mime_types'        => '',
                        ),
                        array(
                            'key'               => 'field_home5f190068af32f',
                            'label'             => 'Food Category Target URL',
                            'name'              => 'food-category-target-url-1',
                            'type'              => 'url',
                            'instructions'      => '',
                            'required'          => 0,
                            'conditional_logic' => 0,
                            'wrapper'           => array(
                                'width' => '',
                                'class' => '',
                                'id'    => '',
                            ),
                            'default_value'     => '',
                            'placeholder'       => '',
                        ),
                        array(
                            'key'               => 'field_home5f18ebee51fd4',
                            'label'             => 'Category 2',
                            'name'              => '',
                            'type'              => 'tab',
                            'instructions'      => '',
                            'required'          => 0,
                            'conditional_logic' => 0,
                            'wrapper'           => array(
                                'width' => '',
                                'class' => '',
                                'id'    => '',
                            ),
                            'placement'         => 'top',
                            'endpoint'          => 0,
                        ),
                        array(
                            'key'               => 'field_home5f18ebfc51fd5',
                            'label'             => 'Food Category Title',
                            'name'              => 'food-category-title-2',
                            'type'              => 'text',
                            'instructions'      => '',
                            'required'          => 0,
                            'conditional_logic' => 0,
                            'wrapper'           => array(
                                'width' => '',
                                'class' => '',
                                'id'    => '',
                            ),
                            'default_value'     => 'Sea Food',
                            'placeholder'       => '',
                            'prepend'           => '',
                            'append'            => '',
                            'maxlength'         => '',
                        ),
                        array(
                            'key'               => 'field_home5f18ec2b51fd6',
                            'label'             => 'Food Category Icon',
                            'name'              => 'food-category-icon-2',
                            'type'              => 'image',
                            'instructions'      => '',
                            'required'          => 0,
                            'conditional_logic' => 0,
                            'wrapper'           => array(
                                'width' => '',
                                'class' => '',
                                'id'    => '',
                            ),
                            'return_format'     => 'array',
                            'preview_size'      => 'thumbnail',
                            'library'           => 'all',
                            'min_width'         => '',
                            'min_height'        => '',
                            'min_size'          => '',
                            'max_width'         => '',
                            'max_height'        => '',
                            'max_size'          => '',
                            'mime_types'        => '',
                        ),
                        array(
                            'key'               => 'field_home5f1900b3af330',
                            'label'             => 'Food Category Target URL',
                            'name'              => 'food-category-target-url-2',
                            'type'              => 'url',
                            'instructions'      => '',
                            'required'          => 0,
                            'conditional_logic' => 0,
                            'wrapper'           => array(
                                'width' => '',
                                'class' => '',
                                'id'    => '',
                            ),
                            'default_value'     => '',
                            'placeholder'       => '',
                        ),
                        array(
                            'key'               => 'field_home5f18ec980c2d6',
                            'label'             => 'Category 3',
                            'name'              => '',
                            'type'              => 'tab',
                            'instructions'      => '',
                            'required'          => 0,
                            'conditional_logic' => 0,
                            'wrapper'           => array(
                                'width' => '',
                                'class' => '',
                                'id'    => '',
                            ),
                            'placement'         => 'top',
                            'endpoint'          => 0,
                        ),
                        array(
                            'key'               => 'field_home5f18ecaa0c2d7',
                            'label'             => 'Food Category Title',
                            'name'              => 'food-category-title-3',
                            'type'              => 'text',
                            'instructions'      => '',
                            'required'          => 0,
                            'conditional_logic' => 0,
                            'wrapper'           => array(
                                'width' => '',
                                'class' => '',
                                'id'    => '',
                            ),
                            'default_value'     => 'Snacks',
                            'placeholder'       => '',
                            'prepend'           => '',
                            'append'            => '',
                            'maxlength'         => '',
                        ),
                        array(
                            'key'               => 'field_home5f18ecca0c2d8',
                            'label'             => 'Food Category Icon',
                            'name'              => 'food-category-icon-3',
                            'type'              => 'image',
                            'instructions'      => '',
                            'required'          => 0,
                            'conditional_logic' => 0,
                            'wrapper'           => array(
                                'width' => '',
                                'class' => '',
                                'id'    => '',
                            ),
                            'return_format'     => 'array',
                            'preview_size'      => 'thumbnail',
                            'library'           => 'all',
                            'min_width'         => '',
                            'min_height'        => '',
                            'min_size'          => '',
                            'max_width'         => '',
                            'max_height'        => '',
                            'max_size'          => '',
                            'mime_types'        => '',
                        ),
                        array(
                            'key'               => 'field_home5f1900c8af331',
                            'label'             => 'Food Category Target URL',
                            'name'              => 'food-category-target-url-3',
                            'type'              => 'url',
                            'instructions'      => '',
                            'required'          => 0,
                            'conditional_logic' => 0,
                            'wrapper'           => array(
                                'width' => '',
                                'class' => '',
                                'id'    => '',
                            ),
                            'default_value'     => '',
                            'placeholder'       => '',
                        ),
                        array(
                            'key'               => 'field_home5f18ed070c2d9',
                            'label'             => 'Food Category 4',
                            'name'              => '',
                            'type'              => 'tab',
                            'instructions'      => '',
                            'required'          => 0,
                            'conditional_logic' => 0,
                            'wrapper'           => array(
                                'width' => '',
                                'class' => '',
                                'id'    => '',
                            ),
                            'placement'         => 'top',
                            'endpoint'          => 0,
                        ),
                        array(
                            'key'               => 'field_home5f18ed180c2da',
                            'label'             => 'Food Category Title',
                            'name'              => 'food-category-title-4',
                            'type'              => 'text',
                            'instructions'      => '',
                            'required'          => 0,
                            'conditional_logic' => 0,
                            'wrapper'           => array(
                                'width' => '',
                                'class' => '',
                                'id'    => '',
                            ),
                            'default_value'     => 'Continental Dish',
                            'placeholder'       => '',
                            'prepend'           => '',
                            'append'            => '',
                            'maxlength'         => '',
                        ),
                        array(
                            'key'               => 'field_home5f18ed390c2db',
                            'label'             => 'Food Category Icon',
                            'name'              => 'food-category-icon-4',
                            'type'              => 'image',
                            'instructions'      => '',
                            'required'          => 0,
                            'conditional_logic' => 0,
                            'wrapper'           => array(
                                'width' => '',
                                'class' => '',
                                'id'    => '',
                            ),
                            'return_format'     => 'array',
                            'preview_size'      => 'thumbnail',
                            'library'           => 'all',
                            'min_width'         => '',
                            'min_height'        => '',
                            'min_size'          => '',
                            'max_width'         => '',
                            'max_height'        => '',
                            'max_size'          => '',
                            'mime_types'        => '',
                        ),
                        array(
                            'key'               => 'field_home5f1900e6af333',
                            'label'             => 'Food Category Target URL',
                            'name'              => 'food-category-target-url-4',
                            'type'              => 'url',
                            'instructions'      => '',
                            'required'          => 0,
                            'conditional_logic' => 0,
                            'wrapper'           => array(
                                'width' => '',
                                'class' => '',
                                'id'    => '',
                            ),
                            'default_value'     => '',
                            'placeholder'       => '',
                        ),
                    ),
                ),
        ),
        'location'              => array(
                array(
                    array(
                        'param'    => 'page_template',
                        'operator' => '==',
                        'value'    => 'page-home.php',
                    ),
                ),
        ),
        'menu_order'            => 0,
        'position'              => 'normal',
        'style'                 => 'default',
        'label_placement'       => 'top',
        'instruction_placement' => 'label',
        'hide_on_screen'        => array(
                0  => 'the_content',
                1  => 'excerpt',
                2  => 'discussion',
                3  => 'comments',
                4  => 'revisions',
                6  => 'author',
                7  => 'format',
                8  => 'page_attributes',
                9  => 'featured_image',
                10 => 'categories',
                11 => 'tags',
                12 => 'send-trackbacks',
        ),
        'active'                => true,
        'description'           => '',
        )
    );
    
endif;
